name: monai-0.9.1
channels:
  - conda-forge
  - defaults
  - pytorch
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.3.2=h166bdaf_0
  - anyio=3.6.1=pyhd8ed1ab_1
  - aom=3.4.0=h27087fc_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h0a891b7_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.14=ha878542_0
  - certifi=2022.9.14=pyhd8ed1ab_0
  - cffi=1.15.1=py38h4a40e3a_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - contourpy=1.0.5=py38h43d8883_0
  - cryptography=38.0.2=py38h80a4ca7_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.4.1.50=hed8a83a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.3=py38hfa26641_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.0.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=3.2.4=1
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.37.2=py38h0a891b7_0
  - freetype=2.12.1=hca18f0e_0
  - future=0.18.2=py38h578d9bd_5
  - gettext=0.19.8.1=h73d1719_1008
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.7=hf3e180e_0
  - gst-plugins-base=1.20.2=hcf0ee16_0
  - gstreamer=1.20.3=hd4edc92_2
  - icu=69.1=h9c3ff4c_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.3=pyh210e3f2_0
  - ipython=8.5.0=pyh41d4057_1
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py38h578d9bd_0
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyterlab=3.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_0
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=13.0.1=default_hc23dcda_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.113=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libglib=2.72.1=h2d90d5f_0
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.3=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm13=13.0.1=hf817b99_2
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h753d276_4
  - libprotobuf=3.19.4=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.4.0=h55922b4_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libxslt=1.1.33=h0ef7038_3
  - libzlib=1.2.12=h166bdaf_3
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lxml=4.8.0=py38h0a891b7_2
  - magma=2.5.4=h6103c52_2
  - markupsafe=2.1.1=py38h0a891b7_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.30=h26416b9_1
  - mysql-libs=8.0.30=hbc51c84_1
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.5.0=pyhd8ed1ab_0
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.8.1=hc379101_1
  - ninja=1.11.0=h924138e_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.3.0=h27087fc_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.5=h166bdaf_2
  - p11-kit=0.24.1=hc5aa10d_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py38ha3b2c9c_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h0a891b7_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch-gpu=1.10.0=cuda112py38h0bbbad9_1
  - pytorch-mutex=1.0=cuda
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyzmq=24.0.0=py38hfc09fa9_0
  - readline=8.1.2=h0f457ee_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.3=h4ff8645_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - svt-av1=1.2.1=h27087fc_0
  - tbb=2021.5.0=h924138e_2
  - terminado=0.15.0=py38h578d9bd_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py38h0a891b7_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - unicodedata2=14.0.0=py38h0a891b7_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_3
  - zstd=1.5.2=h6239696_4
  - pip:
      - absl-py==1.4.0
      - accelerate==1.0.1
      - aim==3.27.0
      - aim-ui==3.27.0
      - aimrecords==0.0.7
      - aimrocks==0.5.2
      - aiofiles==24.1.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alembic==1.10.4
      - altair==5.4.1
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==25.3.0
      - base58==2.0.1
      - bitsandbytes==0.45.3
      - blinker==1.6.2
      - bokeh==3.1.1
      - boto3==1.36.12
      - botocore==1.36.12
      - cachetools==5.3.0
      - captum==0.7.0
      - catboost==1.2.2
      - chardet==4.0.0
      - choreographer==1.0.9
      - click==8.1.3
      - clip==1.0
      - cloudpickle==2.2.1
      - cmake==3.27.0
      - colorama==0.4.5
      - colorcet==3.1.0
      - construct==2.10.68
      - construct-typing==0.5.6
      - cucim==23.4.1
      - databricks-cli==0.17.7
      - datasets==3.0.1
      - dill==0.3.8
      - docker==6.1.1
      - dominate==2.9.1
      - driver==0.1.0
      - easyfsl==1.5.0
      - einops==0.6.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - eyepy==0.12.1
      - fastapi==0.115.8
      - filelock==3.8.0
      - fire==0.5.0
      - flask==2.3.2
      - frozenlist==1.4.0
      - fsspec==2023.5.0
      - ftfy==6.1.3
      - gdown==4.5.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.18.0
      - google-auth-oauthlib==1.0.0
      - grad-cam==1.5.0
      - graphviz==0.20.1
      - greenlet==2.0.2
      - grpcio==1.54.0
      - gunicorn==20.1.0
      - h11==0.14.0
      - h5py==3.8.0
      - holoviews==1.17.1
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.14.1
      - idna==2.10
      - imagecodecs==2023.3.16
      - imageio==2.28.1
      - imageio-ffmpeg==0.5.1
      - imbalanced-learn==0.12.4
      - ipywidgets==8.0.7
      - itk==5.3.0
      - itk-core==5.3.0
      - itk-filtering==5.3.0
      - itk-io==5.3.0
      - itk-numerics==5.3.0
      - itk-registration==5.3.0
      - itk-segmentation==5.3.0
      - itsdangerous==2.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyterlab-widgets==3.0.8
      - kaleido==1.0.0
      - kornia==0.7.3
      - kornia-rs==0.1.8
      - langchain==0.2.17
      - langchain-core==0.2.43
      - langchain-ollama==0.1.3
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.147
      - lazy-loader==0.2
      - lightning-utilities==0.9.0
      - linkify-it-py==2.0.3
      - lit==16.0.6
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - logistro==1.1.0
      - lpips==0.1.4
      - mako==1.2.4
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - matplotlib==3.7.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mlflow==2.3.1
      - monai==1.2.0
      - monai-deploy-app-sdk==0.4.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.16
      - narwhals==1.42.0
      - natsort==8.4.0
      - networkx==2.8.6
      - nibabel==5.1.0
      - nptyping==2.5.0
      - numba==0.58.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - oct-converter==0.6.2
      - ollama==0.4.4
      - omegaconf==2.3.0
      - open-clip-torch==2.30.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.8.0.74
      - openpyxl==3.1.5
      - openslide-python==1.1.2
      - orjson==3.10.15
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==1.5.3
      - panel==1.2.3
      - param==2.1.1
      - patsy==1.0.2
      - plotly==5.15.0
      - portpicker==1.6.0
      - pot==0.9.5
      - protobuf==3.20.3
      - pyarrow==17.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydeprecate==0.3.0
      - pydicom==2.3.1
      - pyjwt==2.7.0
      - pynrrd==1.0.0
      - pysankey==0.0.1
      - python-gdcm==3.0.22
      - pytorch-gradcam==0.2.1
      - pytorch-lightning==1.3.8
      - pyviz-comms==3.0.6
      - pywavelets==1.4.1
      - pyyaml==5.4.1
      - querystring-parser==1.2.4
      - regex==2023.5.5
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - restrictedpython==7.4
      - rsa==4.9
      - s3transfer==0.11.2
      - safetensors==0.5.2
      - scikit-image==0.20.0
      - scikit-learn==1.1.2
      - scipy==1.9.1
      - seaborn==0.13.2
      - selenium==4.27.1
      - shap==0.38.1
      - simplejson==3.20.1
      - sklearn==0.0
      - slicer==0.0.7
      - smmap==5.0.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.13
      - sqlparse==0.4.4
      - starlette==0.44.0
      - statsmodels==0.14.1
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - tensorboardx==2.6
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - timm==1.0.13
      - tokenizers==0.20.0
      - torch==2.0.0
      - torchattacks==3.5.1
      - torchinfo==1.7.2
      - torchmetrics==1.1.1
      - torchsummary==1.5.1
      - torchvision==0.15.1
      - tqdm==4.64.1
      - transformers==4.29.0
      - trio==0.27.0
      - trio-websocket==0.12.2
      - triton==2.0.0
      - ttach==0.0.3
      - typeguard==2.13.3
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - uc-micro-py==1.0.3
      - uvicorn==0.33.0
      - visdom==0.2.4
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - websockets==13.1
      - werkzeug==2.3.4
      - widgetsnbextension==4.0.8
      - wsproto==1.2.0
      - xarray==2023.1.0
      - xxhash==3.5.0
      - xyzservices==2025.4.0
      - yarl==1.9.2
prefix: /blue/ruogu.fang/leem.s/conda/envs/monai-0.9.1
